export const REQUEST_LOGIN = "REQUEST_LOGIN"
export const RECEIVE_LOGIN = "RECEIVE_LOGIN"
export const REQUEST_LOGOUT = "REQUEST_LOGOUT"
export const RECEIVE_LOGOUT = "RECEIVE_LOGOUT"

export const ADD_PAYMENT_ORDER = "ADD_PAYMENT_ORDER"

export const ADD_BANK_ACCOUNT = "ADD_BANK_ACCOUNT"
export const REQUEST_BANK_ACCOUNTS = "REQUEST_BANK_ACCOUNTS"
export const RECEIVE_BANK_ACCOUNTS = "RECEIVE_BANK_ACCOUNTS"
